### ISSUE TITLE
Support for Gates of Babylon weapons?

### ISSUE THREAD

**Issue by rustedgoldmc** [FlamingCherry/Witherite#2]
Would it be possible to add support for Witherite versions of the weapons from Gates of Babylon? The link is here: https://www.curseforge.com/minecraft/mc-mods/gate-of-babylon . Also if you want help with textures at all I'm glad to help, I've got some experience with texture packs and far too much free time.

**Comment by FlamingCherry** [comment]
Bruh, curseforge is down again? 😂

In any case, I do not guarantee that I will be able to add support for other mods in the near future. Firstly, I am now busy in real life, and secondly, for a start, I want to finish adding all the vanilla tools and only then somehow start adding support with other mods.

But if I have time, I will see what can be done. Thank you for your request. 😊

**Comment by rustedgoldmc** [comment]
Oh yeah, I of course meant only after the armor and stuff is added. My offer for textures is still open if you want! I'll probably be retexturing them anyway to match the other stuff in my texture pack.

**Comment by FlamingCherry** [comment]
> Oh yeah, I of course meant only after the armor and stuff is added. My offer for textures is still open if you want! I'll probably be retexturing them anyway to match the other stuff in my texture pack.

Thank you, I will contact you if I need help. For now, I want to try painting the textures myself.
