### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Anonymous8560** [FlamingCherry/Witherite#4]
Some things are missing in the 1.16.5 version: Witherite block, enricher witherite block, raw witherite, refined witherite, witherite nugget, piece of damaged nether star, damaged nether star, organic witherite, enriched witherite powder, and enriched witherite ingot.

**Comment by FlamingCherry** [comment]
This is not a bug.  These items were added in version 0.0.5 for Minecraft 1.17.  Earlier versions do not have these items.
