### ISSUE TITLE
Witherite deposits never spawn.

### ISSUE THREAD

**Issue by Liliepond** [FlamingCherry/Witherite#6]
I dug out an entire chunk. None. I checked the code, and it says 2 per chunk, but there's none. The likely issue lies in your genregistry, when you set the spawn y coordinates to YOffset.aboveBottom(1), YOffset.aboveBottom(12)

I believe this is causing the issue. You probably meant to set the height to 12, but at it's current state nothing ever spawns.

**Comment by Liliepond** [comment]
https://github.com/Liliepond/Witherite/releases/tag/0.0.7
Working.

**Comment by FlamingCherry** [comment]
I apologize for this issue, I am not very good at understanding how generation works yet. 

Thank you for the solution. I will release a fixed version when I have time and credit you as the author of fix. 😊

**Comment by Liliepond** [comment]
Thanks alot, I see you're putting alot of effort and work into maintaining this repo, and I thank you for responding so quickly.

**Comment by FlamingCherry** [comment]
> Thanks alot, I see you're putting alot of effort and work into maintaining this repo, and I thank you for responding so quickly.

Thank you. :D
I would answer even faster if I was not busy with work in real life.
