### ISSUE TITLE
1.17.1 sprite

### ISSUE THREAD

**Issue by EhhBeh** [FlamingCherry/Witherite#7]
In the 1.17.1 a lot of sprite are bugged 
![Screenshot (3)](https://user-images.githubusercontent.com/71278233/125752485-f241b8b0-ad3a-4e90-aec9-023892129575.png)

**Comment by FlamingCherry** [comment]
I don’t know how to comment on this and I don’t know how it happened. ~.~

But I have uploaded the fixed version to CurseForge and Modrinth, please download it.

https://www.curseforge.com/minecraft/mc-mods/witherite/files/3389593

**Comment by Liliepond** [comment]
Probably caused when you build directly from the github files, as the enriched textures aren't present here.
I had to decompile a release to get the textures up and running.
