### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Oliver-makes-code** [FlamingCherry/Witherite#9]
Hello, I would like to take over the Witherite project, but I need to relicense your code LGPL, because GPL is incompatible with Minecraft mods. Because of that, I am unable to upload my forked version to Modrinth. Thanks for your help!
Also, I've been trying to contact you on your Discord

**Comment by FlamingCherry** [comment]
Hello. Sorry, I don't use Discord anymore. :(

I changed the license to LGPL in my repository, now you can do the same for yourself.
